name: Test
'on':
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install test dependencies
        run: |
          python -m pip install --disable-pip-version-check editorconfig-checker
          make dev-requirements

      - name: Run tox
        run: |
          make lint-editorconfig
          make test
